Repository intel/xFasterTransformer, pull requests merged in 2024-06, with the labels that each got.

#420 [Kernel] Less compute for Self-Attention (Q * K)
  src/kernels/attention_kernels.h
Labels: enhancement, performance

#430 [Dependency] Update libiomp5.so to `5.0.20230815` contained in mkl.
  src/pytorch/CMakeLists.txt
  src/xfastertransformer/env.py
Labels: dependencies

#421 [Distribute] Add distribute support for continuous batching api.
  include/models.h
  src/models/models.cpp
  src/pytorch/auto_model.h
  src/xfastertransformer/automodel.py
Labels: enhancement, continuous batching

#429 [Layers] Fixed error in yarn
  src/layers/yarn_scaled_rotary_embedding.cpp
  src/layers/yarn_scaled_rotary_embedding.h
Labels: bug

#431 [README] Update readme.
  README.md
  README_CN.md
  examples/cpp/README.md
  examples/pytorch/README.md
  examples/web_demo/README.md
  serving/vllm-xft.md
Labels: documentation

#432 [Dependency] Fix wrong so path returned in `get_env()`.
  src/xfastertransformer/env.py
Labels: dependencies, interface

#433 [Version] v1.7.0.
  CHANGELOG.md
  VERSION
Labels: release

#441 [Model] Fix array out of bounds when rank > 2.
  src/models/models.cpp
Labels: bug, continuous batching

#445 [Version] v1.7.1.
  CHANGELOG.md
  VERSION
Labels: release

#448 [Doc] Add vllm benchmark docs.
  serving/vllm-xft.md
Labels: documentation

#372 [Kernel] Add GPU kernels and enable LLaMA model.
  CMakeLists.txt
  requirements-gpu.txt
  src/common/allocator.h
  src/common/sequence.h
  src/common/transformer_ctx.h
  src/kernels/attention_kernels.cpp
  src/kernels/attention_kernels.h
  src/kernels/rotary_embedding_kernels.cpp
  src/kernels/rotary_embedding_kernels.h
  src/layers/attention.cpp
  src/layers/attention.h
  src/layers/decoder_block.h
  src/layers/decoder_layer.cpp
  src/layers/decoder_layer.h
  src/layers/dist_linear.h
  src/layers/layer_norm.cpp
  src/layers/layer_norm.h
  src/layers/mlp_chatglm2.h
  src/layers/mlp_llama.cpp
  src/layers/mlp_llama.h
  src/layers/mlp_standard.h
  src/layers/rms_norm.cpp
  src/layers/rms_norm.h
  src/layers/rotary_embedding.cpp
  src/layers/rotary_embedding.h
  src/layers/token_embedding.h
  src/models/common_decoder.h
  src/models/llama.cpp
  src/models/llama.h
  src/utils/compile_util.h
  src/utils/debugger.h
  src/utils/decoder_util.h
  src/utils/matmul_helper.h
  src/utils/simple_mem_pool.h
  src/utils/transpose_util.h
  src/utils/type_selector.h
  src/utils/verbose.h
  tests/ut/attention_kernels_test.cpp
  tests/ut/cross_attention_test.cpp
  tests/ut/kv_reorder_test.cpp
  tests/ut/layers_attention_test.cpp
  tests/ut/rotary_embedding_test.cpp
Labels: enhancement, gpu

#453 [Model] Support hybrid model in continuous batching.
  include/abstract_decoder.h
  include/models.h
  src/models/hybrid_model.h
  src/models/models.cpp
Labels: enhancement, continuous batching

#452 [Kernel] Enable continuous batching on single GPU.
  pyproject.toml
  src/common/allocator.h
  src/kernels/rotary_embedding_kernels.cpp
  src/kernels/rotary_embedding_kernels.h
  src/layers/attention.h
  src/layers/decoder_block.h
  src/layers/mlp_chatglm2.h
  src/layers/mlp_llama.h
  src/layers/mlp_standard.h
  src/layers/rms_norm.cpp
  src/layers/rotary_embedding.cpp
  src/models/common_decoder.h
  src/utils/debugger.h
  src/utils/matmul_helper.h
  src/utils/verbose.h
Labels: enhancement, gpu, continuous batching

#456 [Feature] Enable AMX FP16 on next generation CPU
  CMakeLists.txt
  cmake/onednn.cmake
  src/utils/matmul_helper.h
  src/utils/type_selector.h
Labels: enhancement
