Repository intel/xFasterTransformer, pull requests merged in 2024-04, with the labels that each got.

#352 [Version] v1.6.0.
  CHANGELOG.md
  VERSION
Labels: release

#358 [Model] Fix compile error of embeddingForward in YaRNLlama
  src/models/yarn_llama.cpp
Labels: bug

#356 [Common] Add sampling params into group seq.
  src/common/sequence.h
  src/searchers/sampling_params.h
Labels: enhancement

#360 [Benchmark] Calculate throughput using avg latency.
  benchmark/benchmark.py
Labels: benchmark

#359 [GPU] Add GPU build option.
  CMakeLists.txt
  README.md
  cmake/sentencepiece.cmake
Labels: enhancement, gpu

#363 [Common] Refactor sequence.h.
  src/common/sequence.h
Labels: enhancement

#361 [Kernels] Refactor flash attention for continuous batching.
  src/kernels/attention_kernels.h
  src/layers/attention.h
  src/layers/attn_baichuan.h
  src/utils/decoder_util.h
Labels: enhancement

#366 [Model] add interface for seq meta.
  include/abstract_decoder.h
  include/models.h
  src/models/common_decoder.h
  src/models/hybrid_model.h
  src/models/models.cpp
  src/searchers/sampling_params.h
Labels: enhancement
