Repository intel/xFasterTransformer, pull requests merged in 2024-05, with the labels that each got.

#370 [Model] Fix ICX build issue.
  CMakeLists.txt
  include/abstract_decoder.h
  include/abstract_searcher.h
  src/models/baichuan.cpp
  src/models/baichuan.h
  src/models/chatglm.cpp
  src/models/chatglm.h
  src/models/chatglm2.cpp
  src/models/chatglm2.h
  src/models/gemma.cpp
  src/models/llama.cpp
  src/models/model_factory.h
  src/models/opt_decoder.cpp
  src/models/qwen.cpp
  src/models/qwen.h
  src/models/qwen2.cpp
  src/models/qwen2.h
  src/models/yarn_llama.cpp
  src/models/yarn_llama.h
Labels: bug, gpu

#369 [Model] New CommonDecoder::forward impl. skeleton
  src/common/sequence.h
  src/models/common_decoder.h
Labels: enhancement

#371 [Common] New KVCacheMgr to support CB
  src/common/kvcache_mgr.h
Labels: enhancement

#373 [Sampling] Add repetition penalty for new seq type.
  include/models.h
  src/common/sequence.h
  src/models/models.cpp
  src/searchers/search_utils.cpp
  src/searchers/search_utils.h
  tests/ut/CMakeLists.txt
  tests/ut/repetition_penalty_test.cpp
Labels: enhancement

#374 [CMake] Remove evaluation under XFT_BUILD_TESTS option.
  CMakeLists.txt
  ci_build
Labels: test, build

#348 [Kernel][UT] Kernel impl. of crossAttnByHead and unit test for cross attention.
  src/kernels/attention_kernels.h
  tests/ut/cross_attention_test.cpp
Labels: test

#376 [Sampling] Add greedy search for cb path.
  examples/cpp/example.cpp
  include/models.h
  src/common/sequence.h
  src/models/models.cpp
  src/searchers/sampling.cpp
  src/searchers/sampling.h
  src/searchers/search_utils.cpp
Labels: enhancement

#375 [Model/Layer] New forward to support CB (CommonDecoder->DecoderBlock->DecoderLayer->Attention/MLP)
  src/layers/attention.h
  src/layers/decoder_block.h
  src/layers/decoder_layer.h
  src/models/common_decoder.h
Labels: enhancement

#379 [Framework] Code fix to make new path for CB work
  src/common/datatypes.h
  src/common/kvcache_mgr.h
  src/layers/decoder_block.h
  src/models/common_decoder.h
Labels: enhancement, continuous batching

#378 [API] Add LLaMA attention API.
  include/layers_attention.h
  src/layers/attention.cpp
  src/layers/attention.h
  src/layers/decoder_layer.h
  src/layers/rotary_embedding.cpp
  src/models/model_factory.h
  tests/ut/layers_attention_test.cpp
Labels: interface

#381 [Framework] Update set_input for cb.
  include/models.h
  src/common/kvcache_mgr.h
  src/common/sequence.h
  src/models/models.cpp
Labels: enhancement, continuous batching

#382 [Layer] Cross attention impl. for CB
  src/kernels/attention_kernels.h
  src/layers/attention.h
Labels: continuous batching

#388 [Build] Fix namespace build issue.
  src/layers/attention.cpp
Labels: bug, build, continuous batching

#387 [Common] DecoderContext::resize bug fix
  src/common/transformer_ctx.h
  src/layers/attention.h
Labels: bug, continuous batching

#390 [Example] add cb_check example
  examples/cpp/CMakeLists.txt
  examples/cpp/cb_check.cpp
Labels: continuous batching, example

#392 [Example] Fix continuous batching C++ example.
  examples/cpp/cb_check.cpp
Labels: continuous batching, example

#386 [API] Add LLaMA decoder API.
  include/dtype.h
  include/layers.h
  include/layers_attention.h
  src/layers/attention.cpp
  src/layers/decoder_layer.cpp
  tests/ut/layers_test.cpp
Labels: interface

#394 [Model] Check maxLen should be [input len, model max len].
  src/models/models.cpp
Labels: continuous batching

#399 [KVCache] Remove FP32 data type.
  benchmark/README.md
  benchmark/benchmark.py
  evaluation/run_model.sh
  examples/cpp/cb_check.cpp
  examples/cpp/example.cpp
  examples/pytorch/demo.py
  examples/web_demo/demo_utils.py
  src/models/model_factory.h
  src/pytorch/auto_model.h
  src/xfastertransformer/automodel.py
Labels: interface

#402 [Layers] Add alibiSlopes Attn && Flash Attn for CB.
  src/kernels/attention_kernels.h
  src/layers/attention.h
Labels: enhancement, continuous batching

#404 [Interface] Support List[int] and List[List[int]] for set_input_sb.
  include/models.h
  src/models/models.cpp
  src/pytorch/auto_model.h
  src/xfastertransformer/automodel.py
Labels: enhancement, continuous batching, interface

#406 [Example] Fix incorrect tensor dimension with latest interface
  examples/pytorch/demo_offline_cb.py
Labels: continuous batching, example

#410 [xDNN] Release v1.5.0.
  cmake/xdnn.cmake
Labels: performance

#412 [Kenrel] Add FP16 LLaMA YARN rotary_embedding.
  src/kernels/rotary_embedding_kernels.h
  src/layers/yarn_scaled_rotary_embedding.cpp
  src/layers/yarn_scaled_rotary_embedding.h
Labels: enhancement

#409 [Benchmark] Add platform options. Support real model.
  benchmark/README.md
  benchmark/run_benchmark.sh
Labels: benchmark

#416 [Dependency] Update torch to 2.3.0.
  requirements.txt
  setup.py
Labels: dependencies

#422 [xDNN] Release v1.5.1.
  cmake/xdnn.cmake
Labels: enhancement, performance

#415 [Kernel] Add FP16 MHA and MLP kernels.
  CMakeLists.txt
  src/comm_helper/comm_helper.cpp
  src/kernels/gemm_kernel_ext.cpp
  src/kernels/gemm_kernel_ext.h
  src/kernels/gemm_kernel_ext2.cpp
  src/kernels/gemm_kernel_ext3.cpp
  src/utils/matmul_helper.h
  src/utils/messenger.h
  src/utils/shm_reduction.cpp
  src/utils/type_selector.h
Labels: enhancement

#427 [Python] Add `get_env()` to get LD_PRELOAD set.
  src/pytorch/CMakeLists.txt
  src/xfastertransformer/__init__.py
  src/xfastertransformer/env.py
Labels: enhancement

#418 Add --padding and fix bug
  benchmark/run_benchmark.sh
Labels: bug, benchmark

#424 [Layers] Fixed the seg fault error when running with more than 4 ranks
  src/layers/mlp_chatglm2.h
  src/utils/messenger.h
  src/utils/split_util.h
Labels: bug
